apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: githubstats-default
  namespace: default
spec:
  destination:
    name: githubstats
  precedence: 1
  route:
  - labels:
      version: v2
    weight: 100      