/*
 * EventManager
 * EventManager is a simple API allowing user to interact with EventManager.  It allows user to:  * register/unregister an EventProvider with EventManager  * get the information of a registered EventProvider  * list all the registered EventProvider  * send event to the EventBus via EventManager
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.auth;

import io.swagger.client.Pair;

import java.util.stream.Stream;

public interface Authentication {

    /**
     * Authentication settings as header parameters.
     *
     * @return header parameters as stream of pairs
     */
    Stream<Pair> asHeaderParams();

    /**
     * Authentication settings as query parameters.
     *
     * @return query parameters as stream of pairs
     */
    Stream<Pair> asQueryParams();
}
